apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ivolve-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Amr-Awad/jenkins_updateManifest.git'
    targetRevision: main  # or whichever branch you're using
    path: ./  # 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ivolve  # This will deploy to the ivolve namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
